### ISSUE TITLE
selenium standalone throwing error: Error: Callback was already called

### ISSUE THREAD

**Issue by gowthamraj198** [vvo/selenium-standalone#489] opened 2020-11-24 12:19 UTC
## Issue

I am trying to run my WDIO tests. When i run the tests in local it is running fine. But when i Try to run in docker (CentOS) below error is thrown.

I am using nodejs version v15.2.1

## Error logs
root/node_modules/selenium-standalone/lib/install.js:626
      cb(new Error("Could not request headers from " + url + ": " + err));
      ^
Error: Callback was already called.
    at /root/node_modules/selenium-standalone/node_modules/async/dist/async.js:318:36
    at Request.<anonymous> (/root/node_modules/selenium-standalone/lib/install.js:626:7)
    at Object.onceWrapper (node:events:436:26)
    at Request.emit (node:events:329:20)
    at Request.EventEmitter.emit (node:domain:467:12)
    at IncomingMessage.<anonymous> (/root/node_modules/request/request.js:1079:12)
    at IncomingMessage.emit (node:events:329:20)
    at IncomingMessage.EventEmitter.emit (node:domain:467:12)
    at TLSSocket.socketCloseListener (node:_http_client:430:13)
    at TLSSocket.emit (node:events:341:22)

## Steps to reproduce: 
running command inside docker - npx wdio ./config/desktopWeb.config.js

**Comment by christian-bromann** [comment] 2020-11-24 12:22
duplicate of #488

**Closed** 2020-11-25 11:08 UTC

**Comment by gauravgandhi1315** [comment] 2022-04-28 21:26
@gowthamraj198 Were you able to fix this issue?

**Comment by gowthamraj198** [comment] 2022-04-29 01:48
@gauravgandhi1315 i dont remember how i fixed this. but i dont get any errors now
