### ISSUE TITLE
Error during download of Selenium Standalone jar and browser drivers with v6.22.1

### ISSUE THREAD

**Issue by gulatirajat** [vvo/selenium-standalone#515] opened 2020-11-29 19:57 UTC
I am using WebDriverIO v6. The underlying components are on latest version.
I am using @wdio/selenium-standalone-service@**6.10.3**, which in-turn installs selenium-standalone@^**6.22.1** as a dependency.
System: **macOS Catalina 10.15.7 (19H15)**

The selenium standalone jar as well as the browser drivers do not get downloaded during npm install. When I start with the test execution, I am expecting these components to get downloaded as per the versions mentioned in - lib/default-config.js,
instead I see the following errors:

**On the console log**:
RequestError: connect ECONNREFUSED 
    at ClientRequest.<anonymous> (/Users/XXX/XXX/XXX/node_modules/got/dist/source/core/index.js:953:111)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:326:22)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at ClientRequest.origin.emit (/Users/XXX/XXX/XXX/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {
  code: 'ECONNREFUSED',
  timings: {
    start: 1606677555847,
    socket: 1606677555849,
    lookup: 1606677556141,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1606677572207,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 292,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 16360
    }
  }
}

**Errors in the wdio.log:**
DEBUG @wdio/utils:initialiseServices: initialise service "selenium-standalone" as NPM package
INFO @wdio/cli:launcher: Run onPrepare hook
ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: Could not download https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-macos.tar.gz

If I explicitly install the previous version - 6.20.1, I do not see the errors and the components get downloaded.

**Comment by mgrybyk** [comment] 2020-11-29 20:08
Are you able to manually download geckodriver?

**Comment by gulatirajat** [comment] 2020-11-30 02:35
Able to manually download geckodriver.
This error log has geckodriver, however may very well could have been for Selenium standalone jar or Chromedriver.

1. Clean remove existing node_modules  .
2. Ensure following versions in package.json 
@wdio/cli - 6.10.2
@wdio/sync - 6.10.0
 @wdio/local-runner - 6.10.2 
@wdio/selenium-standalone-service - 6.10.3 (=> dependency - "selenium-standalone": "^6.22.1")
@wdio/cucumber-6.8.0 
@wdio/junit-reporter - 6.8.1 
@wdio/spec-reporter - 6.8.1

3. Install using - npm i
4.  Start the test execution - ./node_modules/.bin/wdio ./test/config/wdio.local.conf.js

Download operation results in the mentioned error.

**Comment by mgrybyk** [comment] 2020-11-30 06:21
It doesn't result any error for me

**Comment by web-padawan** [comment] 2020-11-30 21:17
Got the same error when using v6.22.1:

```
   Error: Missing /home/runner/work/web/web/packages/test-runner-webdriverio/node_modules/selenium-standalone/.selenium/chromiumedgedriver/latest-x64-msedgedriver
      at /home/runner/work/web/web/packages/test-runner-webdriverio/node_modules/selenium-standalone/lib/check-paths-existence.js:16:2
```

**Comment by mgrybyk** [comment] 2020-11-30 21:19
@web-padawan is it linux?
Try upgrading to 6.22.2

**Comment by web-padawan** [comment] 2020-11-30 21:52
I already upgraded to 6.22.2 but still getting this error when running tests in GitHub Actions.

See example: https://github.com/modernweb-dev/web/pull/1033/checks?check_run_id=1476572545

Note, the PR contains `yarn.lock` bump so it shouldn't be a caching issue, and the build passes locally on MacOS 10.15

**Comment by mgrybyk** [comment] 2020-11-30 22:13
@web-padawan it should not be an issue anymore. Check your dependencies and make sure you are not installing edge

**Comment by web-padawan** [comment] 2020-12-01 07:56
Thanks, as I mentioned, locally it works so it's most likely a GitHub Actions issue in my case.

**Comment by lviana-menlosecurity** [comment] 2020-12-01 19:06
@mgrybyk, I'm installing 6.22.2 on Ubuntu and it seems to install just fine (albeit without the edge driver):
`ubuntu@jenkins-ova-test-node8:/opt/selenium$ sudo npm install selenium-standalone@latest -g
/usr/local/bin/selenium-standalone -> /usr/local/lib/node_modules/selenium-standalone/bin/selenium-standalone
/usr/local/bin/start-selenium -> /usr/local/lib/node_modules/selenium-standalone/bin/start-selenium
+ selenium-standalone@6.22.2
updated 1 package in 2.799s
ubuntu@jenkins-ova-test-node8:/opt/selenium$ sudo selenium-standalone install
----------
selenium-standalone installation starting
----------

---
selenium install:
from: https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
to: /usr/local/lib/node_modules/selenium-standalone/.selenium/selenium-server/3.141.59-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/87.0.4280.20/chromedriver_linux64.zip
to: /usr/local/lib/node_modules/selenium-standalone/.selenium/chromedriver/latest-x64-chromedriver
---
firefox install:
from: https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
to: /usr/local/lib/node_modules/selenium-standalone/.selenium/geckodriver/latest-x64-geckodriver

[====================] 100%      https://chromedriver.storage.googleapis.com/87.0.4280.20/chromedriver_linux64.zip
[====================] 100%      https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
[====================] 100%      https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz


-----
selenium-standalone installation finished`

However, when I run a test, it still fails with the error to find the latest edge driver (which is not being installed by the command above):
`(node:11909) UnhandledPromiseRejectionWarning: Error: Missing /usr/local/lib/node_modules/selenium-standalone/.selenium/chromiumedgedriver/latest-x64-msedgedriver
    at /usr/local/lib/node_modules/selenium-standalone/lib/check-paths-existence.js:16:29
    at suppressedCallback (fs.js:227:5)
    at FSReqCallback.oncomplete (fs.js:171:23)`

The issue above happens for us on 6.22.0, 6.22.1, and 6.22.2. However, if instead I install 6.21.0, then the edge driver is indeed installed, and tests work just fine. Therefore, the issue seems to have been introduced by the code change that added support for "latest" as a version.

**Comment by mgrybyk** [comment] 2020-12-01 19:20
That's weird, edge should not be neither installed nor started. Are you starting or installing it yourself?
Try deleting node modules folder

**Comment by lviana-menlosecurity** [comment] 2020-12-01 19:39
@mgrybyk, edge is **not** getting installed, as expected (and we don't even use it). The problem is that once we start a **chrome** test, it fails immediately, and when you look at the selenium logs you see that the reason is because it was checking for edge existence (is it even supposed to check for that?), and since it's not there it fails. (and again, up until 6.21.0, it looks like this did **not** happen presumably because edge was getting installed).

**Comment by mgrybyk** [comment] 2020-12-01 19:56
Have you tried 6.22.2?

**Comment by lviana-menlosecurity** [comment] 2020-12-01 20:01
Yes, the issue happens on 6.22.0, 6.22.1, and 6.22.2. Up until 6.21.0 it was fine.

**Comment by mgrybyk** [comment] 2020-12-01 20:16
Thanks for the logs and investigation.
Fixed in 6.23.0

**Closed by mgrybyk** 2020-12-01 20:16 UTC
Labels: need more info

**Comment by gulatirajat** [comment] 2020-12-03 19:41
The original problem, for which I had logged this issue - I was able to resolve it using the following lines of code in my 'wdio.local.conf.js':

==============================================================================
require('global-agent/bootstrap');

global.GLOBAL_AGENT.HTTP_PROXY = 'http://<mycorpproxy>:<port>';
global.GLOBAL_AGENT.HTTPS_PROXY = 'http://<mycorpproxy>:<port>';
global.GLOBAL_AGENT.NO_PROXY = '127.0.0.1,localhost';
==============================================================================

Was not expecting the proxy to be a problem since all was fine till 6.20.1 and the above configs are not needed for v6.20.1 on the same machine.

**Comment by mgrybyk** [comment] 2020-12-03 20:04
Not quite sure what is that. Are you using some custom system proxy and had to disable it?

**Comment by gulatirajat** [comment] 2020-12-03 22:37
https://webdriver.io/docs/proxy.html
https://github.com/gajus/global-agent

This setup is for connection between the test script and the browser driver (or WebDriver endpoint) in case outbound traffic goes through a corporate proxy.
